#               _                    _
#     _ __ ___ | |    ___   __ _  __| | ___ _ __
#    | '_ ` _ \| |   / _ \ / _` |/ _` |/ _ \ '__| Developed by:
#    | | | | | | |__| (_) | (_| | (_| |  __/ |    Markineo
#    |_| |_| |_|_____\___/ \__,_|\__,_|\___|_|    [v. 1.0.1]
#
database:
  type: 'MySQL'
  host: 'localhost'
  port: 3306
  database: 'mloader'
  user: "root"
  password: ""